### ISSUE TITLE
Stations and vehicles lists are empty

### ISSUE THREAD

**Issue by alexey-lukyanenko** [dzavalishin/jdrive#109]

**Comment by dzavalishin** [comment]
Thought I've fixed that. What kind of transport it was?

**Comment by dzavalishin** [comment]
I see. List of vehicles that belong to station is empty.

**Comment by dzavalishin** [comment]
Empty stations list is fixed. For vehicle lists I need more info on bug - I've checked bus/train lists, both global and per station and they're working.

**Comment by alexey-lukyanenko** [comment]
I'm sorry for late answer. Even global player vehicle list is empty.

**Comment by alexey-lukyanenko** [comment]
![image](https://user-images.githubusercontent.com/20643927/132103717-042cd8f0-87d7-4446-9793-edd830b73055.png)
The build from the latest commit.

**Comment by alexey-lukyanenko** [comment]
I have a fix for this. Could you please open repo so that I can push a branch and create a pull request?

**Comment by alexey-lukyanenko** [comment]
Please disregard the above. I will create a PR via fork workflow.
