### ISSUE TITLE
Rails on slopes are displayed weird

### ISSUE THREAD

**Issue by alexey-lukyanenko** [dzavalishin/jdrive#115]
Behavior of train on such slope tile is unpredictable.
![image](https://user-images.githubusercontent.com/20643927/132141664-b090c645-be68-4587-b7c6-a7d7c598fe4f.png)
![image](https://user-images.githubusercontent.com/20643927/132141672-9b5e4b97-b451-492f-af39-31f10c058bce.png)
On the last image the rail is straight and train goes ahead regardless of displayed rail shape.

**Comment by dzavalishin** [comment]
This basically means that error is in the display part, not rail state as such...

**Comment by dzavalishin** [comment]
Repeated it

**Comment by dzavalishin** [comment]
Can it be related to #52? Something is wrong with tile state display in both cases.

**Comment by dzavalishin** [comment]
![image](https://user-images.githubusercontent.com/11458393/132965922-81a16482-04a7-45f6-8cb6-7bf629222f2c.png)

type         = 1 - ok, rail
height      = 1 - **this one is the only candidate to be wrong?** Also there's `extra` field which is not printed here
m1           = 0 - ok, owner
m2           = c - ok, on desert
m3           = 0 - ok, conventional rails
m4           = 0 - pbs reserve, irrelevant
m5           = 2 - ok, track in Y direction

**Comment by dzavalishin** [comment]
dbg: type         = 1
dbg: height       = 1
dbg: m1           = 0
dbg: m2           = c
dbg: m3           = 0
dbg: m4           = 0
dbg: m5           = 2
dbg: extra        = 1
dbg: slope/h      = 4/8

Slope type 4 according to tileh.png is just is what we see. It means that there's not a display error, but rail building terraform error

**Comment by alexey-lukyanenko** [comment]
The train can go there without obstacles, so maybe this is the incorrect bits placed...

**Comment by dzavalishin** [comment]
As far as I see train does not check tile form at all, just connection of rails. :) And internally rails are connected ok for such places.

**Comment by dzavalishin** [comment]
in CmdBuildSingleRail():
CheckRailSlope seems to be ok, returns terraform price, so terraforming is assumed
Cmd.CMD_LANDSCAPE_CLEAR does not terraform - just removes trees

I don't see actual terraforming code during rail building. Cost is assumed, but no land changing.
Will debug DrawTile_Track...

**Comment by dzavalishin** [comment]
Current suspect is DrawTrackBits(), for it was rewritten (not identical to C version).

**Comment by dzavalishin** [comment]
![image](https://user-images.githubusercontent.com/11458393/132981974-42b3130d-d899-4abc-bef0-b423dccfa27f.png)

- No real terraforming is done. Tile is 'dinamically terraformed' during painting.
- Fence shows how tile should be painted, but it does not.
- Error must be in DrawTrackBits(), but rewritten part seems to be correct, at least for this case (tileh == 14)
- Current suspect is GetRailFoundation()
-

**Comment by dzavalishin** [comment]
Fixed part of error in `GetRailFoundation()`

```
if(bits == TRACK_BIT_DIAG1) return 15+i;
if(bits == TRACK_BIT_DIAG2) return 15+i+1;
```

This case is painted better:
![image](https://user-images.githubusercontent.com/11458393/132982436-d36b9cc9-6629-4b50-8a26-954e034b4f16.png)

**Comment by dzavalishin** [comment]
OMG, I DID IT! :)
![image](https://user-images.githubusercontent.com/11458393/132991526-616f3a81-067b-46ec-9b67-888f8a6ff7d0.png)

**Comment by alexey-lukyanenko** [comment]
Wow!

**Comment by dzavalishin** [comment]
One char fix. :)
