### ISSUE TITLE
This repository violates OpenTTD's license; please fix ASAP

### ISSUE THREAD

**Issue by TrueBrain** [dzavalishin/jdrive#140]
Sorry to also bother you here too, but I cannot stress enough how important this is.

Initially we mentioned this in https://www.tt-forums.net/viewtopic.php?p=1248233#p1248233 and via Discord, but I should have done this in your repository from the start. My apologies for not realizing this earlier.

OpenTTD is licensed under GPLv2, and by that contract, any derivative work has to be licensed under (a compatible) GPLv2 license too. Your code is (obviously) a derivative. But, your code is currently licensed under MIT, and as such, is in violation of OpenTTD's license.
See https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility for more details on what is possible. Be mindful of the footnotes.

Please address this issue ASAP. As you currently only have one other contributor, it is still easy to ask @alexey-lukyanenko if they mind you relicensing from MIT to GPLv2. If you would get more contributors, this becomes harder and harder.

Please act now. Don't delay this. I can understand this is not your primary concern, as you just want to code and have fun; and licensing is rarely classified as fun. But the sooner you get this over with, the sooner we can all enjoy working for OpenTTD and their ports!

Thank you.

**Comment by dzavalishin** [comment]
Thank you for a reminder, did it just a second ago.
