### ISSUE TITLE
Town growth: roads are not connected

### ISSUE THREAD

**Issue by dzavalishin** [dzavalishin/jdrive#71]
![image](https://user-images.githubusercontent.com/11458393/131133974-8f3043fa-cb0e-439b-be1c-1e38c19a58c2.png)

**Comment by dzavalishin** [comment]
OpenTTD generates towns with a road grid. Current code in NextTTD generates one long road with no interconnections. It seems that it depends on random number generation, as I found no relevant code modifications.

**Comment by alexey-lukyanenko** [comment]
I will take a look at this
