### ISSUE TITLE
Aircraft main sprite is not paint sometimes on earth

### ISSUE THREAD

**Issue by dzavalishin** [dzavalishin/jdrive#79]
Aircraft shadow is overpainting aircraft itself on earth sometimes

**Comment by dzavalishin** [comment]
Aircraft taxi - sometimes shadow is painted over aircraft itself

**Comment by dzavalishin** [comment]
Apparently there is not a sprite sort bug. Turning aircraft shadow unit off shows that aircraft itself is not being painted sometimes when on earth.

**Comment by alexey-lukyanenko** [comment]
The same is for train loco. At tile edges loco hides.

**Comment by alexey-lukyanenko** [comment]
Main sprite and his shadow were at the same map position and map saved only the latest object - the shadow.
